// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "project-management-platform/internal/models"

	mock "github.com/stretchr/testify/mock"

	mongo "go.mongodb.org/mongo-driver/mongo"

	options "go.mongodb.org/mongo-driver/mongo/options"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// ActivityRepository is an autogenerated mock type for the ActivityRepository type
type ActivityRepository struct {
	mock.Mock
}

// Aggregate provides a mock function with given fields: ctx, pipeline
func (_m *ActivityRepository) Aggregate(ctx context.Context, pipeline []primitive.M) ([]primitive.M, error) {
	ret := _m.Called(ctx, pipeline)

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 []primitive.M
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.M) ([]primitive.M, error)); ok {
		return rf(ctx, pipeline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.M) []primitive.M); ok {
		r0 = rf(ctx, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]primitive.M)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []primitive.M) error); ok {
		r1 = rf(ctx, pipeline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx, filter
func (_m *ActivityRepository) Count(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountWithFilter provides a mock function with given fields: ctx, filter
func (_m *ActivityRepository) CountWithFilter(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountWithFilter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, activity
func (_m *ActivityRepository) Create(ctx context.Context, activity *models.Activity) (*mongo.InsertOneResult, error) {
	ret := _m.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Activity) (*mongo.InsertOneResult, error)); ok {
		return rf(ctx, activity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Activity) *mongo.InsertOneResult); ok {
		r0 = rf(ctx, activity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Activity) error); ok {
		r1 = rf(ctx, activity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ActivityRepository) Delete(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*mongo.DeleteResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *mongo.DeleteResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByEntityID provides a mock function with given fields: ctx, entityType, entityID
func (_m *ActivityRepository) DeleteByEntityID(ctx context.Context, entityType string, entityID primitive.ObjectID) (*mongo.DeleteResult, error) {
	ret := _m.Called(ctx, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByEntityID")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, primitive.ObjectID) (*mongo.DeleteResult, error)); ok {
		return rf(ctx, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, primitive.ObjectID) *mongo.DeleteResult); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, primitive.ObjectID) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindWithFilter provides a mock function with given fields: ctx, filter, opts
func (_m *ActivityRepository) FindWithFilter(ctx context.Context, filter primitive.M, opts *options.FindOptions) ([]*models.Activity, error) {
	ret := _m.Called(ctx, filter, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindWithFilter")
	}

	var r0 []*models.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, *options.FindOptions) ([]*models.Activity, error)); ok {
		return rf(ctx, filter, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, *options.FindOptions) []*models.Activity); ok {
		r0 = rf(ctx, filter, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, *options.FindOptions) error); ok {
		r1 = rf(ctx, filter, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEntityID provides a mock function with given fields: ctx, entityType, entityID, limit, skip
func (_m *ActivityRepository) GetByEntityID(ctx context.Context, entityType string, entityID primitive.ObjectID, limit int64, skip int64) ([]*models.Activity, error) {
	ret := _m.Called(ctx, entityType, entityID, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for GetByEntityID")
	}

	var r0 []*models.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, primitive.ObjectID, int64, int64) ([]*models.Activity, error)); ok {
		return rf(ctx, entityType, entityID, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, primitive.ObjectID, int64, int64) []*models.Activity); ok {
		r0 = rf(ctx, entityType, entityID, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, primitive.ObjectID, int64, int64) error); ok {
		r1 = rf(ctx, entityType, entityID, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ActivityRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.Activity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*models.Activity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *models.Activity); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID, limit, skip
func (_m *ActivityRepository) GetByUserID(ctx context.Context, userID primitive.ObjectID, limit int64, skip int64) ([]*models.Activity, error) {
	ret := _m.Called(ctx, userID, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*models.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int64, int64) ([]*models.Activity, error)); ok {
		return rf(ctx, userID, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int64, int64) []*models.Activity); ok {
		r0 = rf(ctx, userID, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, int64, int64) error); ok {
		r1 = rf(ctx, userID, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByWorkspaceID provides a mock function with given fields: ctx, workspaceID, limit, skip
func (_m *ActivityRepository) GetByWorkspaceID(ctx context.Context, workspaceID primitive.ObjectID, limit int64, skip int64) ([]*models.Activity, error) {
	ret := _m.Called(ctx, workspaceID, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for GetByWorkspaceID")
	}

	var r0 []*models.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int64, int64) ([]*models.Activity, error)); ok {
		return rf(ctx, workspaceID, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int64, int64) []*models.Activity); ok {
		r0 = rf(ctx, workspaceID, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, int64, int64) error); ok {
		r1 = rf(ctx, workspaceID, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecentActivity provides a mock function with given fields: ctx, workspaceID, hours, limit
func (_m *ActivityRepository) GetRecentActivity(ctx context.Context, workspaceID primitive.ObjectID, hours int, limit int64) ([]*models.Activity, error) {
	ret := _m.Called(ctx, workspaceID, hours, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentActivity")
	}

	var r0 []*models.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int, int64) ([]*models.Activity, error)); ok {
		return rf(ctx, workspaceID, hours, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int, int64) []*models.Activity); ok {
		r0 = rf(ctx, workspaceID, hours, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, int, int64) error); ok {
		r1 = rf(ctx, workspaceID, hours, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter, limit, skip
func (_m *ActivityRepository) List(ctx context.Context, filter primitive.M, limit int64, skip int64) ([]*models.Activity, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) ([]*models.Activity, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) []*models.Activity); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, int64, int64) error); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewActivityRepository creates a new instance of ActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityRepository {
	mock := &ActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
