// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "project-management-platform/internal/models"

	mock "github.com/stretchr/testify/mock"

	mongo "go.mongodb.org/mongo-driver/mongo"

	options "go.mongodb.org/mongo-driver/mongo/options"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// BoardRepository is an autogenerated mock type for the BoardRepository type
type BoardRepository struct {
	mock.Mock
}

// AddColumn provides a mock function with given fields: ctx, boardID, column
func (_m *BoardRepository) AddColumn(ctx context.Context, boardID primitive.ObjectID, column models.BoardColumn) error {
	ret := _m.Called(ctx, boardID, column)

	if len(ret) == 0 {
		panic("no return value specified for AddColumn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, models.BoardColumn) error); ok {
		r0 = rf(ctx, boardID, column)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Aggregate provides a mock function with given fields: ctx, pipeline
func (_m *BoardRepository) Aggregate(ctx context.Context, pipeline []primitive.M) ([]primitive.M, error) {
	ret := _m.Called(ctx, pipeline)

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 []primitive.M
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.M) ([]primitive.M, error)); ok {
		return rf(ctx, pipeline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.M) []primitive.M); ok {
		r0 = rf(ctx, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]primitive.M)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []primitive.M) error); ok {
		r1 = rf(ctx, pipeline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx, filter
func (_m *BoardRepository) Count(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountWithFilter provides a mock function with given fields: ctx, filter
func (_m *BoardRepository) CountWithFilter(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountWithFilter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, board
func (_m *BoardRepository) Create(ctx context.Context, board *models.Board) (*mongo.InsertOneResult, error) {
	ret := _m.Called(ctx, board)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Board) (*mongo.InsertOneResult, error)); ok {
		return rf(ctx, board)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Board) *mongo.InsertOneResult); ok {
		r0 = rf(ctx, board)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Board) error); ok {
		r1 = rf(ctx, board)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BoardRepository) Delete(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*mongo.DeleteResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *mongo.DeleteResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindWithFilter provides a mock function with given fields: ctx, filter, opts
func (_m *BoardRepository) FindWithFilter(ctx context.Context, filter primitive.M, opts *options.FindOptions) ([]*models.Board, error) {
	ret := _m.Called(ctx, filter, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindWithFilter")
	}

	var r0 []*models.Board
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, *options.FindOptions) ([]*models.Board, error)); ok {
		return rf(ctx, filter, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, *options.FindOptions) []*models.Board); ok {
		r0 = rf(ctx, filter, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Board)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, *options.FindOptions) error); ok {
		r1 = rf(ctx, filter, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BoardRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.Board, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Board
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*models.Board, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *models.Board); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Board)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByWorkspaceID provides a mock function with given fields: ctx, workspaceID
func (_m *BoardRepository) GetByWorkspaceID(ctx context.Context, workspaceID primitive.ObjectID) ([]*models.Board, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByWorkspaceID")
	}

	var r0 []*models.Board
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]*models.Board, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*models.Board); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Board)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissions provides a mock function with given fields: ctx, boardID
func (_m *BoardRepository) GetPermissions(ctx context.Context, boardID primitive.ObjectID) ([]models.BoardPermission, error) {
	ret := _m.Called(ctx, boardID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []models.BoardPermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]models.BoardPermission, error)); ok {
		return rf(ctx, boardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []models.BoardPermission); ok {
		r0 = rf(ctx, boardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BoardPermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, boardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter, limit, skip
func (_m *BoardRepository) List(ctx context.Context, filter primitive.M, limit int64, skip int64) ([]*models.Board, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Board
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) ([]*models.Board, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) []*models.Board); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Board)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, int64, int64) error); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveColumn provides a mock function with given fields: ctx, boardID, columnID
func (_m *BoardRepository) RemoveColumn(ctx context.Context, boardID primitive.ObjectID, columnID string) error {
	ret := _m.Called(ctx, boardID, columnID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveColumn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, string) error); ok {
		r0 = rf(ctx, boardID, columnID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemovePermission provides a mock function with given fields: ctx, boardID, userID
func (_m *BoardRepository) RemovePermission(ctx context.Context, boardID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, boardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, boardID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReorderColumns provides a mock function with given fields: ctx, boardID, columns
func (_m *BoardRepository) ReorderColumns(ctx context.Context, boardID primitive.ObjectID, columns []models.BoardColumn) error {
	ret := _m.Called(ctx, boardID, columns)

	if len(ret) == 0 {
		panic("no return value specified for ReorderColumns")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, []models.BoardColumn) error); ok {
		r0 = rf(ctx, boardID, columns)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *BoardRepository) Update(ctx context.Context, id primitive.ObjectID, update primitive.M) (*mongo.UpdateResult, error) {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.M) (*mongo.UpdateResult, error)); ok {
		return rf(ctx, id, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.M) *mongo.UpdateResult); ok {
		r0 = rf(ctx, id, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.M) error); ok {
		r1 = rf(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateColumn provides a mock function with given fields: ctx, boardID, columnID, column
func (_m *BoardRepository) UpdateColumn(ctx context.Context, boardID primitive.ObjectID, columnID string, column models.BoardColumn) error {
	ret := _m.Called(ctx, boardID, columnID, column)

	if len(ret) == 0 {
		panic("no return value specified for UpdateColumn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, string, models.BoardColumn) error); ok {
		r0 = rf(ctx, boardID, columnID, column)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePermission provides a mock function with given fields: ctx, boardID, permission
func (_m *BoardRepository) UpdatePermission(ctx context.Context, boardID primitive.ObjectID, permission models.BoardPermission) error {
	ret := _m.Called(ctx, boardID, permission)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, models.BoardPermission) error); ok {
		r0 = rf(ctx, boardID, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBoardRepository creates a new instance of BoardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBoardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BoardRepository {
	mock := &BoardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
