// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "project-management-platform/internal/models"

	mock "github.com/stretchr/testify/mock"

	mongo "go.mongodb.org/mongo-driver/mongo"

	options "go.mongodb.org/mongo-driver/mongo/options"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// CommentRepository is an autogenerated mock type for the CommentRepository type
type CommentRepository struct {
	mock.Mock
}

// AddMention provides a mock function with given fields: ctx, commentID, userID
func (_m *CommentRepository) AddMention(ctx context.Context, commentID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, commentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddMention")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, commentID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Aggregate provides a mock function with given fields: ctx, pipeline
func (_m *CommentRepository) Aggregate(ctx context.Context, pipeline []primitive.M) ([]primitive.M, error) {
	ret := _m.Called(ctx, pipeline)

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 []primitive.M
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.M) ([]primitive.M, error)); ok {
		return rf(ctx, pipeline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.M) []primitive.M); ok {
		r0 = rf(ctx, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]primitive.M)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []primitive.M) error); ok {
		r1 = rf(ctx, pipeline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx, filter
func (_m *CommentRepository) Count(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountWithFilter provides a mock function with given fields: ctx, filter
func (_m *CommentRepository) CountWithFilter(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountWithFilter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, comment
func (_m *CommentRepository) Create(ctx context.Context, comment *models.Comment) (*mongo.InsertOneResult, error) {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Comment) (*mongo.InsertOneResult, error)); ok {
		return rf(ctx, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Comment) *mongo.InsertOneResult); ok {
		r0 = rf(ctx, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Comment) error); ok {
		r1 = rf(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CommentRepository) Delete(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*mongo.DeleteResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *mongo.DeleteResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindWithFilter provides a mock function with given fields: ctx, filter, opts
func (_m *CommentRepository) FindWithFilter(ctx context.Context, filter primitive.M, opts *options.FindOptions) ([]*models.Comment, error) {
	ret := _m.Called(ctx, filter, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindWithFilter")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, *options.FindOptions) ([]*models.Comment, error)); ok {
		return rf(ctx, filter, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, *options.FindOptions) []*models.Comment); ok {
		r0 = rf(ctx, filter, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, *options.FindOptions) error); ok {
		r1 = rf(ctx, filter, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAuthor provides a mock function with given fields: ctx, authorID
func (_m *CommentRepository) GetByAuthor(ctx context.Context, authorID primitive.ObjectID) ([]*models.Comment, error) {
	ret := _m.Called(ctx, authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAuthor")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]*models.Comment, error)); ok {
		return rf(ctx, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*models.Comment); ok {
		r0 = rf(ctx, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CommentRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*models.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *models.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByItemID provides a mock function with given fields: ctx, itemID
func (_m *CommentRepository) GetByItemID(ctx context.Context, itemID primitive.ObjectID) ([]*models.Comment, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetByItemID")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]*models.Comment, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*models.Comment); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplies provides a mock function with given fields: ctx, parentID
func (_m *CommentRepository) GetReplies(ctx context.Context, parentID primitive.ObjectID) ([]*models.Comment, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetReplies")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]*models.Comment, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*models.Comment); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter, limit, skip
func (_m *CommentRepository) List(ctx context.Context, filter primitive.M, limit int64, skip int64) ([]*models.Comment, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) ([]*models.Comment, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) []*models.Comment); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, int64, int64) error); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMention provides a mock function with given fields: ctx, commentID, userID
func (_m *CommentRepository) RemoveMention(ctx context.Context, commentID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, commentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMention")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, commentID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *CommentRepository) Update(ctx context.Context, id primitive.ObjectID, update primitive.M) (*mongo.UpdateResult, error) {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.M) (*mongo.UpdateResult, error)); ok {
		return rf(ctx, id, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.M) *mongo.UpdateResult); ok {
		r0 = rf(ctx, id, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.M) error); ok {
		r1 = rf(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommentRepository creates a new instance of CommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRepository {
	mock := &CommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
