// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "project-management-platform/internal/models"

	mock "github.com/stretchr/testify/mock"

	mongo "go.mongodb.org/mongo-driver/mongo"

	options "go.mongodb.org/mongo-driver/mongo/options"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// ItemRepository is an autogenerated mock type for the ItemRepository type
type ItemRepository struct {
	mock.Mock
}

// AddAssignee provides a mock function with given fields: ctx, itemID, userID
func (_m *ItemRepository) AddAssignee(ctx context.Context, itemID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, itemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddAssignee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, itemID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWatcher provides a mock function with given fields: ctx, itemID, userID
func (_m *ItemRepository) AddWatcher(ctx context.Context, itemID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, itemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddWatcher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, itemID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Aggregate provides a mock function with given fields: ctx, pipeline
func (_m *ItemRepository) Aggregate(ctx context.Context, pipeline []primitive.M) ([]primitive.M, error) {
	ret := _m.Called(ctx, pipeline)

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 []primitive.M
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.M) ([]primitive.M, error)); ok {
		return rf(ctx, pipeline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.M) []primitive.M); ok {
		r0 = rf(ctx, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]primitive.M)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []primitive.M) error); ok {
		r1 = rf(ctx, pipeline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx, filter
func (_m *ItemRepository) Count(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountWithFilter provides a mock function with given fields: ctx, filter
func (_m *ItemRepository) CountWithFilter(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountWithFilter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, item
func (_m *ItemRepository) Create(ctx context.Context, item *models.Item) (*mongo.InsertOneResult, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Item) (*mongo.InsertOneResult, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Item) *mongo.InsertOneResult); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Item) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ItemRepository) Delete(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*mongo.DeleteResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *mongo.DeleteResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindWithFilter provides a mock function with given fields: ctx, filter, opts
func (_m *ItemRepository) FindWithFilter(ctx context.Context, filter primitive.M, opts *options.FindOptions) ([]*models.Item, error) {
	ret := _m.Called(ctx, filter, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindWithFilter")
	}

	var r0 []*models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, *options.FindOptions) ([]*models.Item, error)); ok {
		return rf(ctx, filter, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, *options.FindOptions) []*models.Item); ok {
		r0 = rf(ctx, filter, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, *options.FindOptions) error); ok {
		r1 = rf(ctx, filter, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAssignee provides a mock function with given fields: ctx, userID
func (_m *ItemRepository) GetByAssignee(ctx context.Context, userID primitive.ObjectID) ([]*models.Item, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssignee")
	}

	var r0 []*models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]*models.Item, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*models.Item); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByBoardID provides a mock function with given fields: ctx, boardID
func (_m *ItemRepository) GetByBoardID(ctx context.Context, boardID primitive.ObjectID) ([]*models.Item, error) {
	ret := _m.Called(ctx, boardID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBoardID")
	}

	var r0 []*models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]*models.Item, error)); ok {
		return rf(ctx, boardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*models.Item); ok {
		r0 = rf(ctx, boardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, boardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ItemRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*models.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *models.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter, limit, skip
func (_m *ItemRepository) List(ctx context.Context, filter primitive.M, limit int64, skip int64) ([]*models.Item, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) ([]*models.Item, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) []*models.Item); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, int64, int64) error); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveAssignee provides a mock function with given fields: ctx, itemID, userID
func (_m *ItemRepository) RemoveAssignee(ctx context.Context, itemID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, itemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAssignee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, itemID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveWatcher provides a mock function with given fields: ctx, itemID, userID
func (_m *ItemRepository) RemoveWatcher(ctx context.Context, itemID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, itemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWatcher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, itemID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchText provides a mock function with given fields: ctx, query, limit, skip
func (_m *ItemRepository) SearchText(ctx context.Context, query string, limit int64, skip int64) ([]*models.Item, error) {
	ret := _m.Called(ctx, query, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for SearchText")
	}

	var r0 []*models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*models.Item, error)); ok {
		return rf(ctx, query, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*models.Item); ok {
		r0 = rf(ctx, query, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, query, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *ItemRepository) Update(ctx context.Context, id primitive.ObjectID, update primitive.M) (*mongo.UpdateResult, error) {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.M) (*mongo.UpdateResult, error)); ok {
		return rf(ctx, id, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.M) *mongo.UpdateResult); ok {
		r0 = rf(ctx, id, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.M) error); ok {
		r1 = rf(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateFieldValue provides a mock function with given fields: ctx, itemID, fieldValue
func (_m *ItemRepository) UpdateFieldValue(ctx context.Context, itemID primitive.ObjectID, fieldValue models.ItemFieldValue) error {
	ret := _m.Called(ctx, itemID, fieldValue)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFieldValue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, models.ItemFieldValue) error); ok {
		r0 = rf(ctx, itemID, fieldValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePosition provides a mock function with given fields: ctx, id, position
func (_m *ItemRepository) UpdatePosition(ctx context.Context, id primitive.ObjectID, position int) error {
	ret := _m.Called(ctx, id, position)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int) error); ok {
		r0 = rf(ctx, id, position)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewItemRepository creates a new instance of ItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRepository {
	mock := &ItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
