package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"

	"project-management-platform/internal/models"
)

// SavedFilterRepository is an autogenerated mock type for the SavedFilterRepository type
type SavedFilterRepository struct {
	mock.Mock
}

// CreateIndexes provides a mock function with given fields: ctx
func (_m *SavedFilterRepository) CreateIndexes(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateIndexes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSavedFilter provides a mock function with given fields: ctx, filter
func (_m *SavedFilterRepository) CreateSavedFilter(ctx context.Context, filter *models.SavedFilter) error {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CreateSavedFilter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.SavedFilter) error); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSavedFilter provides a mock function with given fields: ctx, filterID, userID
func (_m *SavedFilterRepository) DeleteSavedFilter(ctx context.Context, filterID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, filterID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSavedFilter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, filterID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DuplicateSavedFilter provides a mock function with given fields: ctx, filterID, newUserID, newName
func (_m *SavedFilterRepository) DuplicateSavedFilter(ctx context.Context, filterID primitive.ObjectID, newUserID primitive.ObjectID, newName string) (*models.SavedFilter, error) {
	ret := _m.Called(ctx, filterID, newUserID, newName)

	if len(ret) == 0 {
		panic("no return value specified for DuplicateSavedFilter")
	}

	var r0 *models.SavedFilter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) (*models.SavedFilter, error)); ok {
		return rf(ctx, filterID, newUserID, newName)
	} else {
		r0 = ret.Get(0).(*models.SavedFilter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) error); ok {
		r1 = rf(ctx, filterID, newUserID, newName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMostUsedFilters provides a mock function with given fields: ctx, workspaceID, entityType, limit
func (_m *SavedFilterRepository) GetMostUsedFilters(ctx context.Context, workspaceID primitive.ObjectID, entityType string, limit int64) ([]*models.SavedFilter, error) {
	ret := _m.Called(ctx, workspaceID, entityType, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMostUsedFilters")
	}

	var r0 []*models.SavedFilter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, string, int64) ([]*models.SavedFilter, error)); ok {
		return rf(ctx, workspaceID, entityType, limit)
	} else {
		r0 = ret.Get(0).([]*models.SavedFilter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, string, int64) error); ok {
		r1 = rf(ctx, workspaceID, entityType, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicSavedFilters provides a mock function with given fields: ctx, workspaceID, entityType
func (_m *SavedFilterRepository) GetPublicSavedFilters(ctx context.Context, workspaceID primitive.ObjectID, entityType string) ([]*models.SavedFilter, error) {
	ret := _m.Called(ctx, workspaceID, entityType)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicSavedFilters")
	}

	var r0 []*models.SavedFilter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, string) ([]*models.SavedFilter, error)); ok {
		return rf(ctx, workspaceID, entityType)
	} else {
		r0 = ret.Get(0).([]*models.SavedFilter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, string) error); ok {
		r1 = rf(ctx, workspaceID, entityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSavedFilter provides a mock function with given fields: ctx, filterID
func (_m *SavedFilterRepository) GetSavedFilter(ctx context.Context, filterID primitive.ObjectID) (*models.SavedFilter, error) {
	ret := _m.Called(ctx, filterID)

	if len(ret) == 0 {
		panic("no return value specified for GetSavedFilter")
	}

	var r0 *models.SavedFilter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*models.SavedFilter, error)); ok {
		return rf(ctx, filterID)
	} else {
		r0 = ret.Get(0).(*models.SavedFilter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, filterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSavedFilterByName provides a mock function with given fields: ctx, userID, workspaceID, entityType, name
func (_m *SavedFilterRepository) GetSavedFilterByName(ctx context.Context, userID primitive.ObjectID, workspaceID primitive.ObjectID, entityType string, name string) (*models.SavedFilter, error) {
	ret := _m.Called(ctx, userID, workspaceID, entityType, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSavedFilterByName")
	}

	var r0 *models.SavedFilter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string, string) (*models.SavedFilter, error)); ok {
		return rf(ctx, userID, workspaceID, entityType, name)
	} else {
		r0 = ret.Get(0).(*models.SavedFilter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string, string) error); ok {
		r1 = rf(ctx, userID, workspaceID, entityType, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSavedFilters provides a mock function with given fields: ctx, userID, workspaceID, entityType
func (_m *SavedFilterRepository) GetUserSavedFilters(ctx context.Context, userID primitive.ObjectID, workspaceID primitive.ObjectID, entityType string) ([]*models.SavedFilter, error) {
	ret := _m.Called(ctx, userID, workspaceID, entityType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSavedFilters")
	}

	var r0 []*models.SavedFilter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) ([]*models.SavedFilter, error)); ok {
		return rf(ctx, userID, workspaceID, entityType)
	} else {
		r0 = ret.Get(0).([]*models.SavedFilter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) error); ok {
		r1 = rf(ctx, userID, workspaceID, entityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementUsageCount provides a mock function with given fields: ctx, filterID
func (_m *SavedFilterRepository) IncrementUsageCount(ctx context.Context, filterID primitive.ObjectID) error {
	ret := _m.Called(ctx, filterID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementUsageCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, filterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSavedFilter provides a mock function with given fields: ctx, filterID, updates
func (_m *SavedFilterRepository) UpdateSavedFilter(ctx context.Context, filterID primitive.ObjectID, updates *models.SavedFilter) error {
	ret := _m.Called(ctx, filterID, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSavedFilter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, *models.SavedFilter) error); ok {
		r0 = rf(ctx, filterID, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
