// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "project-management-platform/internal/models"

	mock "github.com/stretchr/testify/mock"

	mongo "go.mongodb.org/mongo-driver/mongo"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// WorkspaceRepository is an autogenerated mock type for the WorkspaceRepository type
type WorkspaceRepository struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, workspaceID, userID, role
func (_m *WorkspaceRepository) AddMember(ctx context.Context, workspaceID primitive.ObjectID, userID primitive.ObjectID, role string) error {
	ret := _m.Called(ctx, workspaceID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) error); ok {
		r0 = rf(ctx, workspaceID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with given fields: ctx, filter
func (_m *WorkspaceRepository) Count(ctx context.Context, filter primitive.M) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, workspace
func (_m *WorkspaceRepository) Create(ctx context.Context, workspace *models.Workspace) (*mongo.InsertOneResult, error) {
	ret := _m.Called(ctx, workspace)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Workspace) (*mongo.InsertOneResult, error)); ok {
		return rf(ctx, workspace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Workspace) *mongo.InsertOneResult); ok {
		r0 = rf(ctx, workspace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Workspace) error); ok {
		r1 = rf(ctx, workspace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WorkspaceRepository) Delete(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*mongo.DeleteResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *mongo.DeleteResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *WorkspaceRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.Workspace, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*models.Workspace, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *models.Workspace); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *WorkspaceRepository) GetByUserID(ctx context.Context, userID primitive.ObjectID) ([]*models.Workspace, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*models.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]*models.Workspace, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*models.Workspace); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMembers provides a mock function with given fields: ctx, workspaceID
func (_m *WorkspaceRepository) GetMembers(ctx context.Context, workspaceID primitive.ObjectID) ([]models.WorkspaceMember, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []models.WorkspaceMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]models.WorkspaceMember, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []models.WorkspaceMember); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WorkspaceMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter, limit, skip
func (_m *WorkspaceRepository) List(ctx context.Context, filter primitive.M, limit int64, skip int64) ([]*models.Workspace, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) ([]*models.Workspace, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, int64, int64) []*models.Workspace); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.M, int64, int64) error); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: ctx, workspaceID, userID
func (_m *WorkspaceRepository) RemoveMember(ctx context.Context, workspaceID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, workspaceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, workspaceID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *WorkspaceRepository) Update(ctx context.Context, id primitive.ObjectID, update primitive.M) (*mongo.UpdateResult, error) {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.M) (*mongo.UpdateResult, error)); ok {
		return rf(ctx, id, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.M) *mongo.UpdateResult); ok {
		r0 = rf(ctx, id, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.M) error); ok {
		r1 = rf(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMemberRole provides a mock function with given fields: ctx, workspaceID, userID, role
func (_m *WorkspaceRepository) UpdateMemberRole(ctx context.Context, workspaceID primitive.ObjectID, userID primitive.ObjectID, role string) error {
	ret := _m.Called(ctx, workspaceID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) error); ok {
		r0 = rf(ctx, workspaceID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkspaceRepository creates a new instance of WorkspaceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceRepository {
	mock := &WorkspaceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
